### ISSUE TITLE
Apache jsvc compatibility (Include class inside root of capsule)

### ISSUE THREAD

**Issue by rmuchall** [puniverse/capsule#100]
Hi there,

Problem:
Is it possible to include a specific class at the root of the "built" capsule?
e.g. so I can include MyClazz.class

fat-capsule.jar
-> META-INF
-> Capsule.class
-> **MyClazz.class**
-> dependency-one.jar
-> dependency-two.jar

Details:
I've built a capsule using the your Gradle plugin (which works perfectly). However I'm experiencing compatibility problems when using Capsule with Apache Commons Daemon. Daemon uses a utility called Jsvc to run Java applications as a service. Jsvc requires a custom class that implements a Daemon interface to be specified as a classpath parameter. However it is unable to find the correct class because it's inside a jar which is inside the capsule (jar in jar). 

example:
jsvc -cp fat-capsule.jar com.example.MyClazz

Many thanks for any assistance you can provide and thanks for Capsule! :)

Apache Commons Daemon: https://commons.apache.org/proper/commons-daemon/
Apache Commons Jsvc: https://commons.apache.org/proper/commons-daemon/jsvc.html

**Comment by circlespainter** [comment]
Have you tried the [`capsule-daemon`](https://github.com/puniverse/capsule-daemon) caplet? It uses  [Apache Commons Daemon](https://commons.apache.org/proper/commons-daemon/)'s `jsvc` on Unix and `procrun` on Windows and I think it could simplify your case a lot.

**Comment by rmuchall** [comment]
Thanks to your suggestion I've successfully integrated my application with capsule-daemon.
The Capsule project and capsule-daemon are awesome - thank you!

**Comment by circlespainter** [comment]
Great, very glad to hear! Thanks
