### ISSUE TITLE
Dependency question

### ISSUE THREAD

**Issue by chrischristo** [puniverse/capsule#102]
So I noticed the following:

If you include an artifact in the manifest's ```Dependencies``` entry then this will be resolved at runtime, except if the declared artifact is contained within the Capsule jar.

Is the above statement correct?

If so, I have a slight problem. People have been requesting capsules that contain their dependencies, however, without the transitive dependencies (i.e they only want their direct dependencies included in the built capsule and **not** the dependencies' dependencies). So the problem is if I list the dependencies in the ```Dependencies``` field but include it in the capsule jar, Capsule (via MavenCapsule) doesn't seem to download the transitive dependencies at runtime and it just assumes that since the root dependency is embedded then the transitive dependencies are also available?

**Comment by pron** [comment]
Yes, I believe your analysis is correct. Can you think of a specification that would address this?

**Comment by chrischristo** [comment]
Well in its simplest I've had numerous request to support reactor projects (See https://github.com/chrischristo/capsule-maven-plugin/issues/28). These typically involve having a module with submodules where one submodule will contain the plugin config in the pom xml to do the build. Anyway, regardless of that, they typically need a situation where they have a built capsule that includes the root dependencies but not the transitive dependencies.

So for e.g lets say we have ArtifactA, ArtifactB, ArtifactC and ArtifactD.

A depends on B & C. And C depends on D.

So the built capsule for A will have B & C embedded however D **not** embedded as that needs to be resolved at runtime.

So I guess the idea is that ArtifactC is listed in the ```Dependencies``` as its dependencies need to be resolved. However at the moment Capsule doesn't do this as it determines that its been fully resolved since the root dependency is embedded in the Capsule.

I guess the solution would be to check if the transitive dependencies are also embedded or available in the cache?

**Comment by pron** [comment]
As supporting this in the Maven caplet may not be trivial, I'd like to first understand the requirement better, as it's hard for me to grasp its importance:

1. Where is the transitive dependency information coming from? If it's in a Maven repository, then it contains the non-transitive dependencies, too (to get their metadata), so it has to be consulted anyway and the metadata downloaded. The only thing you save is downloading the JARs themselves. Why is that so important?

2. If the direct dependencies are made by the capsule's author anyway, why not simply embed them in the capsule and list the transitive dependencies only in `Dependencies`, as they are known to the author?

**Comment by chrischristo** [comment]
1. It seems that users want to embed direct dependencies which may or may not be in a maven repo. Or in other words some of the direct dependencies may just be some sub project they are building themselves so will potentially not be in a maven repo, and then some of the other direct dependencies may just be standard libs from maven central.

So for e.g:

my-project-capsule.jar
--my-sub-project.jar (not in a maven repo and which depends on google-guava.jar)
--apache-commons.jar (in maven central and depends on various other jars)

So the above capsule jar only includes its two direct dependencies (and any of the transitive dependencies such as google-guava.jar and the various jars that apache-commons depends on are **not** included and need to be resolved at runtime).

I would imagine getting the dependency info of apache-commons.jar would be a case of getting the info from maven/aether from maven central.

However, the my-sub-project.jar, it seems that perhaps extracting the ```pom.xml``` from the jar is a possibility. It seems maven includes the ```pom.xml``` when it builds the jars.

So perhaps from a technical perspective, the MavenCapsule can first try and check against the dependency info from using Aether. If it can't resolve the direct dependency, it can then check to see if there is a ```pom.xml``` file inside and then resolve the transitive dependencies using Aether based on the info gathered from the pom.

2. Yes this is something I was thinking of. The maven plugin takes a flag ```<transitive>false</transitive>``` which means to not embed the transitive dependencies in the capsule jar. So, for this scenario, the plugin could, rather pre-emptively, just include the transitive dependencies in the ```Dependencies``` manifest entry. Although somehow it feels a little dirty to include transitive dependencies in the ```Dependencies``` entry. To me, this entry is synonymous with Direct-Dependencies. The manifest is supposed to define, cleanly, the app, so someone opening up the capsule jar and reading the manifest should know all the info about the capsule.

3. Picking up on my qualms with point 2, perhaps we can define a new (optional) manifest entry called ```TransitiveDependencies``` which could list all the transitive dependencies (to the last branch). So the process could be something be like so:

(a) Read the ```Dependencies``` manifest entry, and for each entry, if it is embedded in the capsule, move to the next one. If it is not embedded, then resolve it (and its transitive dependencies - unless the ```TransitiveDependencies``` entry exists).

(b) Read the ```TransitiveDependencies``` manifest entry (if exists) and for each entry download the jar (without its transitive dependencies). The contract is that if the ```TransitiveDependencies``` exists then this will contain in full and exhaustively **all** the transitive dependencies that the capsule needs, and **not** just some.

By listing **all** the direct dependencies and **all** the transitive dependencies (exhaustively), then the MavenCapsule knows exactly what dependency jars to download already without needing to resolve any transitive dependencies. I wonder if that will have any performance benefits? Otherwise, without the list of exhaustive transitive dependencies, then MavenCapsule has to resolve all the transitive dependencies via the dependency info from the direct dependencies.

I'm thinking this could potentially turn into a case of moving some of the Aether dependency resolution time from the MavenCapsule runtime process to the build process - think that's a win imo, what do you think?

**Comment by pron** [comment]
> To me, this entry is synonymous with Direct-Dependencies. The manifest is supposed to define, cleanly, the app, so someone opening up the capsule jar and reading the manifest should know all the info about the capsule.

But if the subprojects are embedded in the capsule, then their dependencies *are* direct dependencies of the capsule, and precisely the kind of information that should be listed in `Dependencies`.

> So perhaps from a technical perspective, the MavenCapsule can first try and check against the dependency info from using Aether

A simpler spec would be for the Maven caplet to search `pom.xml`s of embedded JARs for dependencies which it would then resolve.

> it can then check to see if there is a pom.xml file inside and then resolve the transitive dependencies using Aether based on the info gathered from the pom.

The Maven caplet already supports dependencies listed in a `pom.xml` file found in the capsule's root. You're suggesting reading dependencies listed in pom files embedded in the capsule's embedded JARs. This is an interesting feature idea, and should not be too hard to implement in the Maven caplet, but, while I'm not rejecting it, there's a clear argument against: the capsule's dependencies would then not be easily gleaned from information found in the manifest or the root pom.

**Comment by chrischristo** [comment]
Hmm somehow I've been used to the concept of categorizing out dependencies based on being direct or indirect, or in other words, the root dependencies and the transitive dependencies. 

This idea for me generally comes from the maven ```pom.xml```, where you only define the root dependencies in the ```<dependencies>``` tag. These root dependencies are what I would call direct dependencies and the transitive dependencies are what I would call indirect dependencies, as their classes are not called on directly by the main project. 

And for me, even dependencies of subprojects are in my opinion still indirect dependencies of the main project as again their classes are not called directly by the main project. They are however of course direct dependencies of the subprojects.

> But if the subprojects are embedded in the capsule, then their dependencies _are_ direct dependencies of the capsule, and precisely the kind of information that should be listed in ```Dependencies```.

So based on my definitions above I would **not** classify the dependencies of the subprojects direct dependencies of the capsule. For me, the capsule relates to **one** specific artifact, namely here, the main project. The subprojects are just dependencies. And in actuality a capsule could also be built for a subproject.

For capsule, the ```MANIFEST.MF``` is essentially its info/package file akin to the ```pom.xml``` for maven and a ```package.json``` for node. So its role is to provide concise info about the artifact. I feel this is quite important as this type of thing has become a standard across other tools.

Therefore, on that basis, the ```Dependencies``` entry should clearly define something, whether that is purely its direct dependencies or all of its dependencies (direct or indirect). To be honest, I think I'm fine either way, just think it would make sense to have consistency. So ideally its not a case where users are doing either or - we should have a standard. An argument to keep it as only pure dependencies is that it would be inline with the same ```<dependencies>``` tag in maven.

**Comment by pron** [comment]
> So based on my definitions above I would not classify the dependencies of the subprojects direct dependencies of the capsule. For me, the capsule relates to one specific artifact, namely here, the main project. The subprojects are just dependencies. And in actuality a capsule could also be built for a subproject.

But a capsule *is* a single artifact, and not a source artifact but a deployment, or binary artifact, and anything that is not embedded in the capsule is a dependency of the capsule, and the roots of those are the direct dependencies of the capsule. 

In any event, the pertinent question is this: should the `Dependencies` manifest attribute or the root pom be the *only* places where capsule dependencies are listed, or could more dependencies be listed in pom files inside embedded JARs? 

If we decide the latter should be supported then the feature is not too hard to implement, I believe (as the caplet already supports reading dependencies listed in poms).

**Comment by chrischristo** [comment]
Well I do feel like the Maven Caplet should resolve all dependency jars needed by the capsule to run correctly. Or more specifically, resolve the dependencies that weren't provided with the capsule at build time. 

Dependency info is essentially declared in three places; the manifest file, the root pom.xml and finally the embedded dependencies. What I mean by the latter is by embedding a jar within the capsule, you're essentially saying that the capsule requires this jar and thus logically, the capsule will need all of that jar's dependencies also.

So the question is how to get info on the embedded jar? Naturally as we've said, check existence of the pom.xml inside. Its also possible that the embedded jar might be a capsule too and thus might have a manifest file with the ```Dependencies``` entry ;). So I'd say check that too.

**Comment by pron** [comment]
> Its also possible that the embedded jar might be a capsule too and thus might have a manifest file with the Dependencies entry ;). So I'd say check that too. 

Well, for now capsules don't support embedded capsules (only wrapped capsules, but that's completely different).

> So the question is how to get info on the embedded jar? Naturally as we've said, check existence of the pom.xml inside.

Alright, so now that we have at least a vague spec, could you open an issue for this feature in the Maven caplet project and link back to this discussion?

**Comment by chrischristo** [comment]
Ok thanks @pron appreciate the help!
