### ISSUE TITLE
Publish Capsule.class in Github releases

### ISSUE THREAD

**Issue by martinpaljak** [puniverse/capsule#103]
So that it could be included easily in external projects, that are not based on maven.

**Comment by circlespainter** [comment]
`Capsule.class` is already published in the `co.paralleluniverse:capsule:<version>` artifacts in Maven Central and you don't need Maven to obtain it, you can e.g. `wget http://central.maven.org/maven2/co/paralleluniverse/capsule/1.0.1/capsule-1.0.1.jar` and then extract the class, or build a script to do it all for you (or possibly there's already a public command/script to download a ZIP and extract). Or you can build it by cloning the git repo and `gradle build`.

Why is that not convenient enough?

**Comment by pron** [comment]
I've added the capsule jar to the [latest release](https://github.com/puniverse/capsule/releases/tag/v1.0.2), but I'm going to need to remember doing it... In any event, as @circlespainter said, you can wget the file from Maven as easily as from GitHub.

**Comment by martinpaljak** [comment]
@pron Travis can do that easily. https://docs.travis-ci.com/user/deployment/releases

Yes I can extract the jar but if the whole point of the jar is to distribute the class, why not make it available separately as well.
