### ISSUE TITLE
Use of System.exit() in Capsule.java prevents calling capsules from exec-maven-plugin

### ISSUE THREAD

**Issue by stolp** [puniverse/capsule#107]
As Capsule.java is using the following code in its `main()` method I am unable to call a capsule using the exec-maven-plugin exec:java goal, since my build process is suddenly aborted:

```
    public static final void main(String[] args) {
        System.exit(main0(args));
    }
```
As this call will terminate the Java VM, it will also terminate the build process that calls it. Surely this will influence other build tools as well (Ant, Gradle etc.) which are trying to execute capsuled code without forking it.

I am aware that it is desirable that exit codes are propagated to the caller. A possible solution would be to make `main0()` a public static method so users at least have a choice here between exit codes and sudden VM termination.

**Comment by circlespainter** [comment]
What's your use case for calling the capsule during the build and wouldn't "exec:exec" work for you rather than "exec:java"?

**Comment by stolp** [comment]
exec:java is able to take a command line argument instead of individual argument tags.

As the amount of arguments is determined dynamically during the build, I have to rely on this feature. For the same reason maven-antrun-plugin is ruled out.

**Comment by circlespainter** [comment]
OK I see now, why are you calling a capsule though rather than directly a class from the project?

**Comment by stolp** [comment]
The project is distributed as a capsule, which we are consuming in our build as a dependency: [https://github.com/nuxeo/gatling-report](https://github.com/nuxeo/gatling-reportl)

**Comment by circlespainter** [comment]
OK. Could you submit a PR that changes the `main0` access modifier then, so that you can rightfully claim the improvement? It'll be merged straight away.

**Comment by pron** [comment]
The new code has been deployed to sonatype (`1.0.4-SNAPSHOT`)
