### ISSUE TITLE
NullPointerException on windows

### ISSUE THREAD

**Issue by jmost** [puniverse/capsule#49]
The method windowsJavaHomesHeuristics calls the method getJavaHomes. The method getJavaHomes can return null. When it does, then windowsJavaHomesHeuristics will try to call allHomes.putAll with this null value, which results in a NullPointerException (in HashMap.putMapEntries, which calls m.entrySet()).

The solution I tried is simple: check the result of getJavaHomes and only call putAll when the result is not null.

**Comment by narbsy** [comment]
You can work around this issue by explicitly setting `capsule.java.home`, which avoids the resolution issues, whereas setting %JAVA_HOME% will not.
