### ISSUE TITLE
Running a capsule fat jar after the first time produces stack-blowing recursion

### ISSUE THREAD

**Issue by chrisfjones** [puniverse/capsule#55]
Please see this simple project: https://github.com/chrisfjones/capsule-stackoverflow-test
.. for reproduction.

Essentially, when running a capsule fat jar more than once; an infinite recursion is created between:
	at Capsule.buildAppCacheDir(Capsule.java:1558)
	at Capsule.getAppCache(Capsule.java:1531)
	at Capsule.buildAppCacheDir0(Capsule.java:1576)

In case this is environment specific:
```
$ mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T09:29:23-08:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
```

**Comment by pron** [comment]
What version of Capsule are you using?

**Comment by chrisfjones** [comment]
Looks like the mvn plugin is pulling 1.0-rc1-SNAPSHOT. If I override to <capsule.version>0.10.0</capsule.version>, things are happy again.

**Comment by pron** [comment]
Yeah, it's the currently unstable dev version. I've already fixed this bug in another branch.

**Comment by chrisfjones** [comment]
Awesome, thanks. I've added https://github.com/chrischristo/capsule-maven-plugin/issues/18 for completeness.
