### ISSUE TITLE
null while processing system property java.home

### ISSUE THREAD

**Issue by ebridges** [puniverse/capsule#57]
Getting this error after upgrading Capsule to version 0.10.0:

```
CAPSULE: Launching app example.FooBarService_0.0.1
CAPSULE: Locking /home/example/.capsule/apps/example.FooBarService_0.0.1/.lock
CAPSULE: Extracting /usr/share/example-service/lib/example-service.jar to app cache directory /home/example/.capsule/apps/example.FooBarService_0.0.1
CAPSULE: Error parsing Java version 1.8.0_31
CAPSULE: Unocking /home/example/.capsule/apps/example.FooBarService_0.0.1/.lock
CAPSULE EXCEPTION: null while processing system property java.home: /usr/lib/jvm/java-8-oracle/jre
java.lang.NullPointerException
	at Capsule.getJavaHomes(Capsule.java:2998)
	at Capsule.findJavaHome(Capsule.java:2125)
	at Capsule.chooseJavaHome0(Capsule.java:2107)
	at Capsule.chooseJavaHome(Capsule.java:2098)
	at Capsule.getJavaHome(Capsule.java:2085)
	at Capsule.getJavaExecutable0(Capsule.java:1633)
	at Capsule.getJavaExecutable(Capsule.java:1625)
	at Capsule.buildJavaProcess(Capsule.java:1579)
	at Capsule.buildProcess0(Capsule.java:1153)
	at Capsule.buildProcess(Capsule.java:1144)
	at Capsule.prelaunch0(Capsule.java:1122)
	at Capsule.prelaunch(Capsule.java:1118)
	at Capsule.prepareForLaunch(Capsule.java:1033)
	at Capsule.launch(Capsule.java:974)
	at Capsule.main0(Capsule.java:296)
	at Capsule.main(Capsule.java:275)
```

`JAVA_HOME` is set:

```
$ echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle
```

Here's the `MANIFEST.MF` for this application:

```
Manifest-Version: 1.0
Main-Class: Capsule
Application-Class: example.FooBarService
Application-Version: 0.0.1
Min-Java-Version: 1.8
JVM-Args:
System-Properties: example.config=/etc/example-service/example.yml
```

**Comment by pron** [comment]
What's your OS? How did you install the JVM?

**Comment by ebridges** [comment]
The method `Capsule#parseJavaVersion()` relies on this regex:

`private static final Pattern PAT_JAVA_VERSION = Pattern.compile("(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(_(?<update>\\d+))?(-(?<pre>[^-]+))?(-(?<build>.+))?");`

This regex fails when given a version of "1.8".

**Comment by ebridges** [comment]
OS is "Ubuntu 14.04.1 LTS" & here are the relevant steps in the playbook to install the JDK:

```
    - name: add oracle jdk repository
      apt_repository: repo=ppa:webupd8team/java

    - name: accept jdk license terms
      shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: set java_home
      lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME={{ java_home }}'

    - name: install ubuntu packages
      apt: pkg={{ item }} state=installed
      with_items:
      - oracle-java8-installer
```

**Comment by pron** [comment]
I think the issue of parsing `"1.8"` is unrelated.

**Comment by ebridges** [comment]
I was using the `sourceCompatibility` field in the Gradle script for the project to set `Min-Java-Version:` field in the manifest.  Even if I set `sourceCompatibility` to be "1.8.0", Gradle rounded that down to "1.8".

**Comment by pron** [comment]
See #58 (just fixed) for the "1.8" issue.

**Comment by ebridges** [comment]
The parsing of the version is the deeper issue that ultimately caused the NPE.

A more insidious issue is that `isMatchingJavaVersion()` is swallowing the `IllegalArgumentException` thrown by `parseJavaVersion()`, thus masking the real problem and leading to an NPE downstream.

**Comment by pron** [comment]
Alright, this has been fixed.
You can either wait for Capsule 1.0 to be released in a few short weeks, copy the fix to your clone of 0.10.0, or change the name of your JVM directory.

**Comment by ebridges** [comment]
Well all I needed to do was change it to use "1.8.0" as the version number, the name of the JDK home directory is a red herring.

You should change the code to not swallow the IllegalArgumentException [being caught here](https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L2298).

**Comment by pron** [comment]
Well, the Java home dir wasn't being recognized either, so those were two actual bugs.

**Comment by ebridges** [comment]
Your call, but I'm not so sure that's the case.  I didn't change the directory in `JAVA_HOME` -- only changed `Min-Java-Version` to be "1.8.0" and it worked.

Maybe I'm just getting lost in the code but if it's not recognizing the Java home dir, how did it get the version string "1.8.0_31" (see above error message)?

**Comment by pron** [comment]
>  how did it get the version string "1.8.0_31"

Because that JVM happened to be the one used to launch the capsule itself, so it got the version number from the `java.version` property.
