### ISSUE TITLE
capsule-desktop - Turns capsules into native desktop apps (experimental) links to 404

### ISSUE THREAD

**Issue by gaborbernat** [puniverse/capsule#64]

**Comment by pron** [comment]
Where is that link?

**Comment by gaborbernat** [comment]
Readme of this repository :)

**Comment by pron** [comment]
I don't see it (I did find it in the docs draft, but that's outdated). That caplet, however, does exist, except it's not released yet.

**Comment by gaborbernat** [comment]
Okay, now it's okay :)
