### ISSUE TITLE
Option for exiting Capsule process after launching the application process (orphaning the child)

### ISSUE THREAD

**Issue by marquiswang** [puniverse/capsule#69]
In our setup where we want to use capsule, we will occasionally have many (double digits) java processes running on one host. If we use capsule to launch these processes with java -jar, they launch with some default heap size, which when multiplied by tens of capsule processes becomes a significant percentage of the physical memory on the host, even though capsule doesn't use very much java heap itself at all.

We can address this somewhat by passing -Xms to the capsule process, but the entire point of using capsule was to be able to encapsulate the java arguments in the jar.

It would be nice to have the option to exit the Capsule process and orphan the child and reclaim the heap of the capsule process.

**Comment by danthegoodman** [comment]
It sounds like you may be looking for the ["capsule trampoline"](https://github.com/puniverse/capsule#the-capsule-execution-process) feature. According to the Readme, it should generate only one process. It is only supported by UNIX systems though.

**Comment by marquiswang** [comment]
Yeah, the trampoline feature does do what we want, but we need it to work for Windows as well, for now.

**Comment by pron** [comment]
> It would be nice to have the option to exit the Capsule process and orphan the child and reclaim the heap of the capsule process.

It would indeed. Unfortunately, the JVM doesn't allow you to do that (you might want to write a caplet that employs native code). So trampolining is the only option without resorting to native. I see no reason why you won't be able to use it on windows. What's UNIX specific isn't the trampoline but the shell script that can be embedded in the JAR. You can write an unembedded batch script that launches the capsule using trampoline (all you need is for the script to launch the capsule with `-Dcapsule.trampoline=true`). If you want to preserve a single file, find a way to do that on Windows, and let me know :)

**Comment by marquiswang** [comment]
You can in fact make a "Really executable" windows batch file/jar by prepending a batch script for running itself as a jar. Sadly, it is difficult/impossible/super-hacky-if-even-possible to have a cross-platform "really executable" jar. We're going to use a separate launcher script that trampolines the jars, I think.
