### ISSUE TITLE
Trampolining fails with spaces in paths

### ISSUE THREAD

**Issue by marquiswang** [puniverse/capsule#70]
The output for trampolining assumes that there are no spaces in either the path to the java executable or in the classpath. This almost always fails in Windows since java is by default installed in "Program Files". 

This will also fail on any platform if there is a space in the Application-Name.

**Comment by pron** [comment]
This bug has been fixed in the current dev version. Can you try to build from sources and test?

**Comment by marquiswang** [comment]
Doesn't quite work for me on Unix. Problem is that putting quotes around the command breaks command substitution:

```
+ "/bin/whoami"
username
$(echo \"/bin/whoami\")
-bash: "/bin/whoami": No such file or directory
```

Didn't test it on Windows.

Or do you recommend trampolining using something else?

**Comment by pron** [comment]
The relevant code is in the `trampolineString` method; I will gladly accept a PR addressing the issue. Otherwise, I'll take a closer look, but it will take at least another week.

**Comment by marquiswang** [comment]
I got it working on both Windows and Unix after switching the single quotes to double quotes in `trampolineString`.

On Unix
```
cmd=$(java -jar -Dcapsule.trampoline foo-capsule.jar)
bash -c "exec $cmd"
```

On Windows (with for loop hack to get output of command in variable)
```
for  /f "delims=" %c in ('java -jar -Dcapsule.trampoline foo-capsule.jar') do (
   CMD /C %c
)
```

**Comment by pron** [comment]
Excellent. Care to submit a PR?
