### ISSUE TITLE
Capsule attribute ATTR_APP_CLASS_PATH does not allow custom directories to be added to the classpath

### ISSUE THREAD

**Issue by pditommaso** [puniverse/capsule#75]
When extending the application CLASSPATH (overriding the `attribute` method and using the `ATTR_APP_CLASS_PATH` attribute) any directory path is automatically suffixed with a `.jar` extension by Capsule. 

This does not allow custom folders to be added to an application CLASSPATH.

**Comment by pron** [comment]
Can you try now (build from source or pull `1.0-rc2-SNAPSHOT` from sonatype)? There might be regressions. I haven't tested yet other than the automated unit tests.

**Comment by pditommaso** [comment]
Um, no. It still appends `.jar` extension to path. 

	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule/1.0-rc2-SNAPSHOT/capsule-1.0-rc2-20150816.190818-18.pom
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150717.095226-6.pom
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule/1.0-rc2-SNAPSHOT/capsule-1.0-rc2-20150816.190818-18.jar
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150717.095226-6.jar

**Comment by pditommaso** [comment]
Also, when the path specified contains dot character the extension is *not* added.

**Comment by pron** [comment]
That sounds like the behavior of the previous version. I see you're using `capsule-maven` which embeds the core capsule and overrides it (I probably need to change that). I've uploaded a fresh re-build of `capsule-maven`. Can you test now?

**Comment by pditommaso** [comment]
I'm unable to pull an updated version of the capsule-maven package: 

	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule/1.0-rc2-SNAPSHOT/capsule-1.0-rc2-20150816.190818-18.jar
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150717.095226-6.jar

**Comment by pron** [comment]
It should be there: `capsule-maven-1.0-rc2-20150816.201448-8`

**Comment by pditommaso** [comment]
I've managed to updated the deps, but the extension is always added :(

	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150816.201448-8.pom
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150816.201448-8.jar

**Comment by pron** [comment]
Can you try now?

**Comment by pditommaso** [comment]
No way. Always the same problem. I need to add a directory to the CLASSPATH, but the suffix `.jar` is automatically added to that folder.

**Comment by pron** [comment]
Can you make sure that you're running the latest code? There is no more any code which adds ".jar" (I believe), and there's [a test](https://github.com/puniverse/capsule/blob/master/capsule/src/test/java/CapsuleTest.java#L882) that verifies specifically that [a library added by a caplet](https://github.com/puniverse/capsule/blob/master/capsule/src/test/java/MyCapsule.java#L49) is handled correctly.

**Comment by pditommaso** [comment]
I've deleted all caches to be sure, however not I'm getting the following error message: 

    : 
	CAPSULE: Transfer failed: capsule.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.codehaus.groovy:groovy-xml::2.3.11 in central (https://repo1.maven.org/maven2/) (for stack trace, run with -Dcapsule.log=verbose)
	CAPSULE: Transfer failed: capsule.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.codehaus.gpars:gpars::1.2.1 in central (https://repo1.maven.org/maven2/) (for stack trace, run with -Dcapsule.log=verbose)
	CAPSULE: Transfer failed: capsule.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact commons-codec:commons-codec::1.6 in central (https://repo1.maven.org/maven2/) (for stack trace, run with -Dcapsule.log=verbose)
	CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: true (for stack trace, run with -Dcapsule.log=verbose)

**Comment by pron** [comment]
That's a related regression...

**Comment by pron** [comment]
That was a related maven-capsule issue. Should be OK now.

**Comment by pditommaso** [comment]
No joy :( 

	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule/1.0-rc2-SNAPSHOT/capsule-1.0-rc2-20150817.053213-19.jar
	Download https://oss.sonatype.org/content/repositories/snapshots/co/paralleluniverse/capsule-maven/1.0-rc2-SNAPSHOT/capsule-maven-1.0-rc2-20150817.053418-9.jar

Unable to download deps. This is the [log](http://pastebin.com/av3DQ7PD) and the [verbose one](http://pastebin.com/cuEVVL6i)

**Comment by pron** [comment]
That's not the latest capsule-maven artifact.

**Comment by pditommaso** [comment]
Finally! Now it is OK. Thanks for your support. 

When the version 1.0 is planned to be released ?

**Comment by pron** [comment]
A week or so -- I hope!
