### ISSUE TITLE
Capsule running fails with exception if jar contains the same file multiple times

### ISSUE THREAD

**Issue by tal-m** [puniverse/capsule#79]
If the jar that includes Capsule.class contains a file multiple times (this happened to me when using the capsule gradle plugin, although I'm not sure why), Capsule will croak with an exception (extractJar will fail when trying to write the file to the appCache the second time).

**Comment by pron** [comment]
I'm not sure this isn't the desired behavior...

**Comment by tal-m** [comment]
I don't think it should be. Putting a file multiple times in a jar is probably a bug, but apparently gradle does do this sometimes (I got the commons-io-1.3.2.jar twice, probably because of some strange dependencies). 

Having capsule crash with an unhelpful error message doesn't seem like the right thing to do, especially since people using it (e.g., me) don't have that much control over the bug that triggers the crash. 

I think a better policy,  in accord with the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle),  would be to continue running if possible (in this case, just ignoring the second occurrence of the file allows capsule to run fine),

I agree that adding a warning message if this occurs is reasonable. If you would like, I can modify my pull request to include the warning message.

**Comment by pron** [comment]
OK, I'm up for that.

**Comment by pron** [comment]
Fixed by #78
