### ISSUE TITLE
Under some conditions, Capsule can try to lock the app cache twice without unlocking first

### ISSUE THREAD

**Issue by tal-m** [puniverse/capsule#81]
(description copied from PR #80, which doesn't solve the bug but does make recovery possible in some cases and makes detection by the user easier)

Bugs in Capsule can cause lockAppCache() to be called twice without unlocking. When this happens, an OverlappingFileLockException is thrown, which is not easily understandable to the average user (and can also misdirect attention from the bug that actually caused this).

An example of this:
In buildSystemProperties(), getAppCache() (which calls lockAppCache()) is called twice: once in buildNativeLibraryPath() and once directly. If an exception is thrown in extractJar() in the first call, it is caught but the unlocking code is bypassed, so the second call tries to enter the lock again.

**Comment by pron** [comment]
Fixed by #80. Thanks!
