### ISSUE TITLE
Website: User guide is out of date

### ISSUE THREAD

**Issue by danthegoodman** [puniverse/capsule#86]
In http://www.capsule.io/user-guide/#getting-capsule, maven dependency should be 
`co.paralleluniverse:capsule:1.0`

In http://www.capsule.io/user-guide/#building-capsule, command should be `gradle install`.

Also, it doesn't look like the site is updated by pushing to the gh-pages branch. For fixes like this in the future, should they be filed as pull requests somewhere or issues like this?

**Comment by pron** [comment]
Thanks! Fixed.
