### ISSUE TITLE
Error searching for JVMs

### ISSUE THREAD

**Issue by telekenetix** [puniverse/capsule#89]
I noticed this when trying to test my capsule when starting it with a lower JVM version than it requires. I was able to duplicate the issue by passing the flag "capsule.jvms=True". 

The capsule that I am calling specifies in the gradle
```gradle
plugins {
    id "us.kirchmeier.capsule" version "1.0-rc1"
}
.....  snip .....
task fatCapsule(type: FatCapsule) {
    applicationClass mainClassName

    capsuleManifest {
        minJavaVersion = '1.8.0'
    }
}
```

On Windows 7 I get
```java
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```

The commandline:
```console
> java -jar -Dcapsule.log=verbose -Dcapsule.jvms=true *****-capsule.jar
CAPSULE: Jar: *****-capsule.jar
CAPSULE: Platform: windows
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: *****
CAPSULE EXCEPTION: Index: 0, Size: 0 while processing system property java.home: C:\Program Files\Java\jre1.8.0_45
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at Capsule.getJavaHomes(Capsule.java:3445)
        at Capsule.getJavaHomes(Capsule.java:3409)
        at Capsule.printJVMs(Capsule.java:987)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at Capsule.runActions(Capsule.java:503)
        at Capsule.main0(Capsule.java:329)
        at Capsule.main(Capsule.java:311)
```

Ubuntu version:
```console
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
```

I get this error
```java
java.lang.IllegalStateException: No match found
```

The commandline:
```console
vagrant@vagrant-ubuntu-trusty-64:~$ java -jar -Dcapsule.log=verbose -Dcapsule.jvms=true *****-capsule.jar
CAPSULE: Jar: *****-capsule.jar
CAPSULE: Platform: linux
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: *****
CAPSULE EXCEPTION: No match found while processing system property java.home: /usr/lib/jvm/java-8-oracle/jre
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536)
        at Capsule.isJavaDir(Capsule.java:3481)
        at Capsule.getJavaHomes(Capsule.java:3442)
        at Capsule.getJavaHomes(Capsule.java:3409)
        at Capsule.printJVMs(Capsule.java:987)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at Capsule.runActions(Capsule.java:503)
        at Capsule.main0(Capsule.java:329)
        at Capsule.main(Capsule.java:311)
```

On both Windows and Ubuntu, running the capsule with the 1.8 JVM (and no printJVMs flag) works flawlessly. However, if I were to ship this and someone were to have the 1.7 JVM on their path and 1.8 JVM also installed, it seems like Capsule would be unable to find the 1.8 JVM required by my application.

**Comment by pron** [comment]
Yes, this is a regression that crept in at some point. We'll issue a fix release soon. 

BTW, are you using Capsule 1.0? The line numbers seem very different from [the 1.0 tag](https://github.com/puniverse/capsule/blob/v1.0.0/capsule/src/main/java/Capsule.java).

**Comment by telekenetix** [comment]
I am using the gradle plugin, which looks like it is targeting 1.0rc1.

**Comment by circlespainter** [comment]
You can still try [using a different Capsule version](https://github.com/danthegoodman/gradle-capsule-plugin/blob/master/DOCUMENTATION.md#using-a-different-capsule-version) although there's https://github.com/danthegoodman/gradle-capsule-plugin/issues/12 so your mileage may vary.

**Comment by telekenetix** [comment]
I switched it to target capsule 1.0 and I got this

```console
Failed to find Premain-Class manifest attribute in *****-capsule.jar
Error occurred during initialization of VM
agent library failed to init: instrument
CAPSULE: Client connection failed.
CAPSULE EXCEPTION: Accept timed out while processing null null: null (for stack trace, run with -Dcapsule.log=verbose)
```

**Comment by pron** [comment]
Yeah, the gradle plugin doesn't fully support Capsule 1.0 yet. You should expect a release in the coming days. In the meantime, you can manually add `Premain-Class: Capsule` to the capsule's manifest (the plugin's Capsule task extends the standard Gradle `Jar` task, so a manifest can be defined the same way).

In any case, this may or may not solve the problem as we've found a regression in this functionality in 1.0, though I'm not yet sure if it's the same exact one.

**Comment by danthegoodman** [comment]
@telekenetix [version `1.0.0` of the gradle plugin](https://plugins.gradle.org/plugin/us.kirchmeier.capsule) is live now and uses capsule 1.0.0. It fixes the `Premain-class` issue at the very least.

**Comment by telekenetix** [comment]
Does 1.0.1 of Capsule fix this?

https://github.com/puniverse/capsule/releases/tag/v1.0.1 claims to have better JDK search.
