### ISSUE TITLE
Error running thin jar

### ISSUE THREAD

**Issue by krisskross** [puniverse/capsule#96]
Hi

I'm building a capsule app using capsule-maven-plugin 0.10.4 and get the following error when trying to run a thin jar for capsule 1.0.1 (fat jar works). I was expecting the artifacts to be downloaded automatically and application would start afterwards.

```bash
$ java -Dcapsule.log=verbose -jar target/capsule-test-1.0.0-SNAPSHOT-capsule-thin.jar 
CAPSULE: Jar: capsule-test/target/capsule-test-1.0.0-SNAPSHOT-capsule-thin.jar
CAPSULE: Platform: linux
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: capsule-test-1.0.0-SNAPSHOT-capsule-thin
CAPSULE: Launching app capsule-test-1.0.0-SNAPSHOT-capsule-thin
CAPSULE: Cleanup
CAPSULE EXCEPTION: Exception while getting attribute Dependencies while processing attribute Capsule-Agent: false
java.lang.RuntimeException: Exception while getting attribute Dependencies
	at Capsule.getAttribute(Capsule.java:2723)
	at Capsule.lookupAllDependencies(Capsule.java:2234)
	at Capsule.prepareForLaunch(Capsule.java:1328)
	at Capsule.launch(Capsule.java:1258)
	at Capsule.main0(Capsule.java:394)
	at Capsule.main(Capsule.java:374)
Caused by: java.lang.RuntimeException: Lookup for com.squareup.okhttp:okhttp:2.5.0 has failed.
	at Capsule.lookup(Capsule.java:3279)
	at Capsule.lookupInAttribute(Capsule.java:3190)
	at Capsule.lookupInAttribute(Capsule.java:3177)
	at Capsule.lookupInAttribute(Capsule.java:3165)
	at Capsule.getAttribute(Capsule.java:2719)
	... 5 more
```

MANIFEST.MF

```bash
Manifest-Version: 1.0
Application-Name: capsule-test-1.0.0-SNAPSHOT-capsule-thin
Application-Class: org.deephacks.Main
Repositories: central(https://repo.maven.apache.org/maven2) 
System-Properties: APP_MAIN_JAR=capsule-test-1.0.0-SNAPSHOT.jar 
Main-Class: Capsule
Dependencies: com.squareup.okhttp:okhttp:2.5.0 io.vertx:vertx-web:3.1.
 0 co.paralleluniverse:capsule:1.0.1 co.paralleluniverse:capsule-maven
 :1.0 
```

**Comment by circlespainter** [comment]
Hi, I'm not a very knowledgeable `capsule-maven` user but I can't see the maven caplet in the manifest. Have you tried using [the 1.0 version](https://github.com/chrischristo/capsule-maven-plugin/releases/tag/capsule-maven-plugin-1.0.0)? Anyway I think you should open the issue on the [plugin project](https://github.com/chrischristo/capsule-maven-plugin) rather than capsule itself.

**Comment by krisskross** [comment]
I wasn't aware of that this project was being used. 

It's just that there is no information to understand what the problem is, and it looks to be happening in the capsule code? Like a parsing or connection error, or similar.

**Comment by chrischristo** [comment]
Hi @krisskross yeah give the 1.0 version of the plugin a shot, we had some issues with the previous versions for anything other than the fat capsule.

**Comment by krisskross** [comment]
@chrischristo Thanks! That worked!
