### ISSUE TITLE
The 'capsule.xyz' properties aren't being read when listed in System-Properties Manifest entry

### ISSUE THREAD

**Issue by chrischristo** [puniverse/capsule#99]
So the various [system properties](http://www.capsule.io/reference/#system-properties), such as `capsule.log` or `capsule.dir` are not being read by Capsule on setup when they are listed in the `System-Properties` manifest entry. 

So for example if i have `System-Properties: capsule.log=verbose` in the manifest entry and then I execute capsule, the logging will not change.

However if I execute Capsule and pass in `-Dcapsule.log=verbose`, then that works.

Is it intentional to not read the properties from the manifest?

**Comment by pron** [comment]
> Is it intentional to not read the properties from the manifest?

Yes! Our intention with capsule is to clearly separate (as much as possible) options that are the application's responsibility from those that are the user's (or deployer's) responsibility. Other deployment products (like Docker) have the same approach. The app says in the manifest: this is what I need to run. The user then says -- on the command line -- this is *how* I want you to run. On occasion, and for convenience, we allow certain deployment-concern defaults to be specified in the manifest. For example, the *default* logging level can be set with the `Capsule-Log-Level` attribute.
